### ISSUE TITLE
Moving/Selecting file issues.

### ISSUE THREAD

**Issue by crimzind** [tagspaces/tagspaces#1069]
If I select multiple files and drag them to a folder, it only moves the one file I clicked instead of the group I have selected.

If I select a group, right click, it deselects all but the one item I clicked on, unless I hold CTRL during the right click.

If I CTRL+Right Click a group, and Move Files, it tells me there was error, but it does actually move the files, but it doesn't update the view/thumbnails to show that.

**Comment by M8be** [comment]
I have the same issue, it hasn't been correct since 3 or 4 versions... I wonder why they add "new abilities" without correct this error when moving multiple files... I just can't use this software if I have to move 1 by 1 all my files, I got thousands of pictures tagged and i just cant move them otherwise that delete all my tags.....

**Comment by uggrock** [comment]
this now works as expected -> closing
