### ISSUE TITLE
Thumbnail Generation

### ISSUE THREAD

**Issue by git748** [tagspaces/tagspaces#1114]
Recently purchased and downloaded Tagspaces Pro to use as a media explorer for an external drive of organized photos.

After connecting the location, Tagspaces doesn't properly generate thumbnails in the .ts folders for the images (generally all jpg or png, <10MB). It generates a few before stopping. When navigating to a new folder without thumbnails, it gives a "Loading or generating thumbnails" message, but freezes there and never actually does this. Additionally, files that begin with a # appear not to have thumbnails created as well.

This is on Windows 10, Tagspaces version 3.5.2

**Comment by uggrock** [comment]
Sometimes TagSpaces has issues with generating thumbs for folder containing large or corrupted JPGs files. We do not have a solution for this for now, but we are still investigating. The solution would be just to find and skip the generation for such files.
As of the # in the name, such files are not fully supported in TagSpaces because the # char is a separator in URLs which are used for the file paths.

**Comment by git748** [comment]
Ok, got it. Thank you for the response. These are my two primary needs for the software at the moment -- if this is the case, will it be possible to get a refund on the Pro version? Thanks.

**Comment by uggrock** [comment]
Sure, If it was purchased in the last 30 days, you can always refund your purchase. Please contact us per email for the refund.

**Comment by git748** [comment]
Will do. Thank you!
