### ISSUE TITLE
Linux MInt Pro Problems

### ISSUE THREAD

**Issue by compixonline** [tagspaces/tagspaces#1126]
Hi,

I've just upgraded to Pro, deleted my old install in the software manager and installed the deb. I'm on Linux Mint. I now have thumbnails but:

1) There seems to be no way of entering the license key provided with Pro
2) Smart tags can not be applied to files
3) Collected tags is not finding new tags I've added, even when actively collected in currnt location.

Any pointers?

Many thanks.

**Comment by uggrock** [comment]
Hi, 
and thanks for purchasing the PRO and supporting this way the project. You do not have to enter the license key anywhere. We do not have a license management service, because this mean tracking the uses of the application and we do not like tracking. I could not get what you mean with the second question, the smart tag can be applied to files and folders, are tags are not automatic tagging if this is what you are expecting. For your third point, it is a bug #1111 in the current version, which should be fixed in the next PRO release.

**Comment by uggrock** [comment]
all issue seems to be fixed -> closing
