### ISSUE TITLE
Mac OS Catalina - It doesn't start at all

### ISSUE THREAD

**Issue by Carsten4278** [tagspaces/tagspaces#1127]
**Describe the bug**
I just downloaded the version 3.5.2.dmg for Mac OS - fine. Installation also fine. 
BUT If I started TagSpaces an window appears "TagSpaces.app" kann nicht geöffnet werden, da Apple darin nicht nach Schadsoftware suchen kann. 

**To Reproduce**
1. Go to 'launchpad'
2. Click on 'TagSpaces.'
<img width="433" alt="Bildschirmfoto 2020-05-19 um 16 50 50" src="https://user-images.githubusercontent.com/65610995/82342063-7823c680-99f1-11ea-9a05-9e49a2b05f4f.png">

**Expected behavior**
A clear and concise description of what you expected to happen. --> TagSpaces doesn't start!

**Screenshots**
If applicable, add screenshots to help explain your problem. --> done

**Desktop Application:**
 - Operating System: [e.g. macOS, Windows 10, Linux, Ubuntu] --> macOS 10.15.4
 - TagSpaces Version [e.g. 3.1.1] 3.5.2

**Additional context**
Add any other context about the problem here. - none

**Comment by uggrock** [comment]
By default macOS does not allow TagSpaces to be executed with a simple double click, because it is currently not digitally signed. To work around this, right-click the TagSpaces.app folder and choose Open, then click Open on the dialog that appears. You need to do this just once.

From our documentation: https://docs.tagspaces.org/installation.html#osx
