### ISSUE TITLE
thumbnails for Zip

### ISSUE THREAD

**Issue by ibaraRinne** [tagspaces/tagspaces#1536]
I have experienced tagspaces Pro for some time. 

I found that the thumb generated in the . ts folder can be changed manually to some extent, but the thumb cannot be added to the compressed package in this way(for example,set an image named "XX.zip.jpg" but it not work)

Do subsequent versions have the opportunity to generate a thumb for the compressed package?Or further, scan the first image in the compressed package as a thumb under my order  manually ?

**Comment by uggrock** [comment]
If you are using the PRO version, you can set a custom thumbnail for every file, regardless of the file type. This is basically the same as creating manually the thumbnail file in the .ts folder (xx.zip.jpg).

In previous version we have an automatic thumbnail extraction from zip files, where if an images was found in the zip it was taken as thumbnail. This functionality is currently disabled because it could lead to performance issues by processing bigger archive files.

**Comment by ibaraRinne** [comment]
well,maybe I forget the".zip"before the".jpg"

and Looking forward the returning of this function
