### ISSUE TITLE
Locations not expanding in Location Manager in 4.0.8 & 4.0.9, when clicking on Location name

### ISSUE THREAD

**Issue by jeron1** [tagspaces/tagspaces#1578]
**Describe the bug**
Locations not expanding in Location Manager in 4.0.8 & 4.0.9, when clicking on Location name; only expand when click on brief case icon next to Location name. Previously, e.g., in 4.0.6, clicking on either Location name or brief case icon would cause a Location to expand to reveal its subfolders (in the Location Manager).

**To Reproduce**
1. Go to Location Manager on left side.
2. Left Click on a Location's name (the text, not the icon), e.g., on "Documents" (not the briefcase icon to its left).
3. Subfolders do not appear underneath the Location name (in the Location Manager)

**Expected behavior**
In 4.0.6, clicking on Documents in the Location Manager would cause the subfolders in Documents to expand under it, with each subfolder listed with a "+" sign. Now, subfolders are revealed only if click on the briefcase icon, to the left of the Location's text. This reduced clickable surface area for Location expansion makes the UI a little less effective for me (i.e., makes it a little slower) because more attention and precision is required for these types of clicks.
![2021-12-09_18-31](https://user-images.githubusercontent.com/73413568/145492450-8bb5338d-1edb-4b8a-8d77-2eec43e8fcd9.png)

**Desktop Application:**
 - Operating System: KDE Neon 5.23
 - TagSpaces Version 4.0.8 & 4.0.9

**Additional context**
I am using my PC for office work. On Windows, I use Lucion Filecenter, but I try to do as much as possible on Linux. The KDE Dolphin UI allows for quick locating of local documents, but it offers only document previews, whereas Filecenter and Tagspaces show entire documents.

**Comment by uggrock** [comment]
We intentionally implemented this in order to allow, opening sub-folders of location which are not current. Imagine you want to move a files to some other location's sub-folder. In version 4.0.6 an bellow, clicking on the location bar will open the sub-folders but will open also the root folder of this location. And your previous folder, containing the file you want to move will be gone. So we decided to differentiate between the two operations: opening a location and opening sub-folder of a given location. We may try to make this somehow more self explaining, maybe with a hover effect on the location's icon.
