### ISSUE TITLE
Gallery Perspective - Ability to delete/tag photos from Gallery Perspective

### ISSUE THREAD

**Issue by Karlstens** [tagspaces/tagspaces#1594]
Although the gallery perspective is great (and I love the ability to have thumbnails listed vertically), the view is a little limited in functionality - in that, I'm hoping to sort through countless photo albums taken over the years using this perspective but still have the right-click delete/move/tag menu available that found in the default perspective. 

My workflow plan is, each week to sit down and;
 - Tag the good photos
 - Delete the bad photos

I suppose any "photo management" related commands (such as deleting/moving/tagging photos) would be useful to the user in this view that you could also think of - for example, it would be freakin' amazing if users were given the ability to touch-up/crop their photos via this perspective, that would be magic! 

Thanks again for such an awesome app. Tagspaces is great!

**Comment by uggrock** [comment]
The file operations are accessible in the file viewer. To show it, you have to open the current file as shown in the attached screenshot.
![Screenshot from 2022-01-16 11-30-45](https://user-images.githubusercontent.com/1249777/149656486-777afc15-5cfd-4e0b-b14d-afb7042863f3.png)

But in v4.1.3 there is an issue, opening the current file will switch the gallery view to the first image in the current directory. This will be fixed in the next release.
.

**Comment by Karlstens** [comment]
My feedback - Clicking on the File Viewer whilst in Gallery Perspective breaks the gallery perspective flow, as for some reason the gallery index cycles all the way back to the first photo upon clicking on the file viewer on a particular image. 

It would be useful if at least keyboard shortcuts could be considered for the gallery perspective so that users can quickly delete unwanted photos whilst cycling through their images.
