### ISSUE TITLE
Tag and file name messed up when "[]" already included in local file name.

### ISSUE THREAD

**Issue by butaixianran** [tagspaces/tagspaces#17]
When a file name already had some "[]" in it, it will messed up in TagSpaces.

for example, file:
[The.Elegant.Universe]2003-BBC-DVD-cd1[14-46-13]

will be like this in tag spaces:
Name: none
Tag: The.Elegant.Universe]2003-BBC-DVD-cd1[14-46-13

That's just so wrong...

I have a lot of files named in this way. some kind of like:
[project-name]file-name[team-name][date].ext
[artist]music-name[collection][date].mp3

It will be much better if TagSpace can parse every pair of "[]" into a tag.  
If do so, these files will be like this in TagSpace:

Name: file-name
Tag: project-name, team-name, date
.
but now it just treat everything between first "[" and last "]" as one tag.

**Comment by hrakotobe** [comment]
By curiosity, I have a question about tag matching. Please ignore if the point has already been discussed to death.

Is there a particular reason (speed I'd guess?) for using indexOx/lastIndexOf to match brackets, instead of a regex (it's messy but it would look like: /\[[\]]*\]]/ )?

I'm looking at this issue because I also had a previous rule of putting each tags is their own brackets (it allowed to keep white space inside tag names) but am in the process of renaming the files to make them play nice with tagspaces.
