### ISSUE TITLE
Tag search not working

### ISSUE THREAD

**Issue by jochenhalwachs** [tagspaces/tagspaces#179]
On the left side (Version 1.9.0) "Dateien mit diesem Tag anzeigen" doesn´t work - also if you have an tag named python (search on the search panel) only get found if you use "?+python" - strange.

**Comment by uggrock** [comment]
? in front of a search query will make it search the subfolders of the current folder. "+python" will show you only files which are tagged with the tag "python". And only "python" will show you files which have the word python in the file name, and since the tags are saved in the file name the result will include also the tagged files.
