### ISSUE TITLE
Sorting search results by Title broken

### ISSUE THREAD

**Issue by Kurufinwe21** [tagspaces/tagspaces#1864]
This is with TagSpaces Pro v. 5.2.4 on Windows 11.

Sorting search results was broken in v. 5.2.3 (see issue #1858). This was fixed in v. 5.2.4, but the fix introduced a new bug.

When making a search (by tag or text), the results cannot be sorted by Title. The other options (Size, Random, etc.) work, but clicking Title in the Sort menu does nothing.

If the folder was already sorted by Title, the search results also get sorted by Title; switching to another method (e.g. Size) works, but then trying to switch back to Title does nothing.

**Comment by sytolk** [comment]
@Kurufinwe21 search results are ordered by relevance (it's more accurate sorting) this is the reason sort by title to be disabled here: https://github.com/tagspaces/tagspaces/blob/develop/app/perspectives/grid-perspective/components/MainContainer.tsx#L293
Maybe we can skip sort byName option in search results? @uggrock

**Comment by Kurufinwe21** [comment]
@sytolk I'm not sure what "relevance" is supposed to mean in this context, and I highly doubt that the _software_ is going to be able to guess what's relevant to me. I just want to find all my files with a certain tag (or combination of tags), and sometimes I want them sorted alphabetically. I can't imagine why such a basic use case should ever stop being supported...

**Comment by sytolk** [comment]
The problem here is that searching library [fuse.js](https://github.com/krisk/Fuse) have search options (fuzzy, semi-strict, strict) with this options search results will be ordered by relevance of the searching keyword. I'm ok to enable additinal sorting functionallity for the search results just is need to rethink how to switch to sort by name and back to sort by relevance.. Maybe it's need to have additinal "Relevance" option in Order By menu and some label that show actial sorting for search results like: "fuzzy search results ordered by Name", or "strict results ordered by Size" default will be "strict results ordered by relevance"

**Comment by uggrock** [comment]
Ok, then let's include a new sorting criteria called "relevance", which will be visible only in search results. It should be also the default sorting for the search result, but one can choose another sorting of the search results, for example by title or file size.
