### ISSUE TITLE
MHTML Security Issue - TagSpaces Web Clipper

### ISSUE THREAD

**Issue by RayH1066** [tagspaces/tagspaces#1886]
Hi
I've noticed a recent change in my browser which is causing issues. It is to do with the MHTML pages I create via 'Tagspaces Web Clipper' of a page I have viewed. I create them for research purposes, sometimes as many as 50 a day. They provide a faithful factual copy. And I have been doing this for years via the app 'Tagspaces Web Clipper' and Brave without issue. Now I receive a 'this file is harmfull warning' and I am asked each time, 'Keep' or 'Discard'. This has started happening in the last few weeks. If I forget to 'keep' and close the browser I receive  Braves 'you are still downloading' message and then I have to click three times in order to keep the MHTML page/file. It is annoying and unnecessary, especially as I the user have created the MHTML page. I have searched through the settings to try and turn that error off and I cannot find anything to do that as  Advanced Settings is no longer 'visible' in the  settings.

Brave have suggested the security alert it is  a Chrome Issue / bug: 
I think it might be this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1172169&q=MHTML&can=2 
Extracted from this list :   https://bugs.chromium.org/p/chromium/issues/list?q=MHTML&can=2

I'm hoping it is something your App can work around?
Thank You
Ray Howell

**Comment by uggrock** [comment]
Hi,

this a general warning which comes since recently in the Chrome based. As much as I know it is not based on the file content, but on the MHTML file format itself. The problem is that if you save a web pages containing a malicious code, the code will be most likely executed on opening the file with a browser (Chrome) supporting MHTML files. The MHTML viewer in the TagSpaces desktop application, makes a kind of sanitation of the MHTML content before presenting it in the app.

The TagSpaces Web Clipper can save MHTML files only in the Chrome based browser, because there is a build-in API/function for creating such files. So the creation in entirely on the browser side and there is nothing we can do, to skip this warning. 

Greetings,
Ilian
