### ISSUE TITLE
The tags should be recursive with sub-directory

### ISSUE THREAD

**Issue by jackzzjack** [tagspaces/tagspaces#213]
When I tag files in a "TAG", I think it should be recursive with sub-directory files. Not just show out the root directory files only.

Thanks.

**Comment by uggrock** [comment]
The only reason this is not the default behaviour, is the fact that recursive search could take a lot of time on a huge directory tree.

**Comment by chhatbar** [comment]
ugrock, when you say it's not the default behaviour; is there a setting which I could tweak to list files corresponding to a TAG for a particular directory, including subdirectories?

**Comment by uggrock** [comment]
Currently we don't have such setting.

**Comment by callocorg** [comment]
Not sure if there may be some confusion in the answer here. You can search recursively all sub-directories by starting the search with a question mark. For example search for "?+MYTAG".

I think this functionality is absolutely crucial and the application would benefit from a setting that determines default recursion vs. not. Why? Because I almost dropped the use of tagspaces entirely when I read this thread. Thankfully I then discovered the recursive search.

**Comment by hybridview** [comment]
I have the same issue. In my use cases, limiting search to one directory level is never useful, and I always organize my directories in a manner that will not hurt performance. I get around this by adding the ? to the search input, but it just adds another step that gets annoying over time. I can change the source locally to alter this behavior, but I think it would be very beneficial to add as an option for other users.

**Comment by uggrock** [comment]
I the next version we search in the sub-folders by default. There is also a switch in the options where this setting can be changed.
