### ISSUE TITLE
Android Source

### ISSUE THREAD

**Issue by Immortalin** [tagspaces/tagspaces#224]
Hi, I am wondering where can I find the android source of tagspace in order to verify its confidentiality and security?

**Comment by uggrock** [comment]
Hi,
the Android version uses the same js code as all other versions of TagSpaces. Only the Cordova packaging is on a separate private repository. This is so because the Android app is the only source where I have some income from this project. But I am thinking heavily to publish the App on Androidpit and completely open source it. If you have real security concerns about the app, feel free to decompile it, the APK is not obfuscated. You can also analyse the traffic around the app. It makes only one network request at start time, for checking if there is a newer version. This check can be disabled in the settings.

I will be glad if you can analyse the JS code for secirity issues.

cheers,
Ilian
