### ISSUE TITLE
Edit tag bugs: not synced and missing from tag library

### ISSUE THREAD

**Issue by jsqliu** [tagspaces/tagspaces#258]
After editing (renaming) a tag in the tag library
1) the corresponding tagged files are not updated
2) the old tag disappears from the tag library despite being still used on files

After editing (renaming) a tag on a file
1) the corresponding tagged files are not updated
2) the new tag does not appear in the tag library

Ubuntu 14.04

**Comment by uggrock** [comment]
Since we are not using a database for the saving of tags but just rename the files, this is the designed behavior. Image that just by renaming of a single file, TagSpaces should go through all locations and renamed all the files containing this files....

In release 1.11.0 tagspaces is collecting all the tags which are not in the taggroups to a taggroup called "Collected tags", so now you can simple reuse our tags.

**Comment by jsqliu** [comment]
Sorry I should have included it above, but I am running release 1.11.0 of tagspaces.  Tags that I add myself are appearing in "Collected tags".  Using the edit tags function results in tags disappearing or not appearing in "Collected tags" resulting in an incomplete tag library.

An essential function is to select a tag in the tag library then "Show files with this tag."  To me it seems logical that an edit tag function should also change the same files shown together.

**Comment by mrfyx** [comment]
Hi, I am in version 2.0.4 on windows and I don't see any `Collectad tags` in tag tab.
If I copy some files (with a file explorer) in the location used by tagspace, tags should appear automatically, right ?
