### ISSUE TITLE
Empty / White Perspective View / No perspective available ?

### ISSUE THREAD

**Issue by lannaen** [tagspaces/tagspaces#396]
Hello,

I tried using TagSpaces, both 32bit & 64bit:
The Perspective screen is white/empty.
The location bar above as well as the folder selector on the left panel both display the right folder.
When I click on the Perspective selector (top right-hand corner), the "list" is white/empty.
As well as the list when I try adding a new perspective from the Options > Perspective tab.

I'm running Windows 10 64bit

Any Idea ?
Thx for the help :)

**Comment by XzK** [comment]
Hello @lannaen,

I have Windows 10 OS 64-bit on my laptop and there is no such problem. Make sure you have the latest version, which is [2.1.1](http://www.tagspaces.org/downloads/) . What kind of files you have in the selected directory?

**Comment by lannaen** [comment]
Hello @XzK :)
I tried navigating in several folders with docx , pdf, jpg, flv or mpg files. And I'm running the 2.1.1, downloaded today :/

**Comment by jlouiskali** [comment]
I am experiencing the same issue:  No perspectives available after I have added a Tag Group.  I also use Windows 10 (64-bit), and I have TagSpaces 2.1.1.   After restoring the initial settings in the General Tab of the Options, the perspectives were back.  But after adding again a Tag Group, they disappeared.
Any idea on how to solve this issue?
Thanks.

**Comment by hybridview** [comment]
Had a similar problem and figured out the problem. TLDR: I had to move the tagspaces folder back into the directory where I first downloaded and ran it from as a temp fix.

When you first download and run tagspaces, it creates some "settings" that seem to create a path reference to the folder you just ran it from. If you move the tagspaces folder later, some functionality is broken due to bad paths (you will see several jscript errors in dev console), and the ability to list available perspectives is one of the broken items. You get a dropdown list asking to choose a perspective, with no items listed. After changing some settings, I then got into a state where perspectives also disappeared from the main view port which meant no files could be shown.

I went into the preferences file (in user/appdata/. . . . folder) and replaced all the old paths with the new paths that I wanted, but could not resolve the issue. I didn't want to waste too much time on this, so did not do any  more research about why changing the paths in the preferences file did not work. Perhaps the path is stored somewhere else too. For now, I am just keeping the tagspaces folder on my desktop (original place it was downloaded to).

**Comment by lannaen** [comment]
Restoring initial settings works. Until you add settings. Very Curious ..

**Comment by phipag2** [comment]
After creating a ".ts" subfolder, exporting the json into this directory and activating the setting to "Loads location metadata" - no file is being found anymore and no perspectives (List, Grid, ...) are in the list.

**Comment by XzK** [comment]
Hello everyone,

Thank you for your patience and cooperation!

We just released a new version of TagSpaces [2.1.3](https://github.com/tagspaces/tagspaces/releases/tag/v2.1.3). I test it on my Windows 10 for both 32-bit and 64-bit versions and have no problem with the Perspective screen.

Would you be so kind to test it and let us know if there is any improvement?

**Comment by uggrock** [comment]
This issue is fixed in 2.1.4.
