### ISSUE TITLE
should not use filename or path as a element's id because it may contains special character

### ISSUE THREAD

**Issue by niphor** [tagspaces/tagspaces#412]
[directories.ui.js#L175](https://github.com/tagspaces/tagspaces/blob/master/data/js/directories.ui.js#L175l)

 filename or path may contains `#` `%` and chinese etc
jquery will throw an exception
such as `jquery.min.js:2 Uncaught (in promise) Error: Syntax error, unrecognized expression: #CDDA不是100%`

**Comment by hybridview** [comment]
I have this problem due to "!" in file name. Every time I update to newest version, I just edit this file to escape those characters before performing the query. My code is below, and only fixes my specific problem. The jq function should be updated to escape/remove ALL special chars. I agree that another identifier should be used so that other languages are supported.

In resources/app/js/directories.ui.js

function jq( myid ) {
    return myid.replace( /(!)/g, "" );
	}
	
  function generateFolderTags(tags, element, menuItem) {
    var $tagsElement = null;
    if (element) {
      var tagId = element.attr('key').split(TSCORE.dirSeparator).pop();
      **$tagsElement = $('#' + jq(tagId));**
      if ($tagsElement.length === 0) {
        $tagsElement = $('<div style="padding: 4px;"></div>');
        $tagsElement.attr('id', tagId);
        var $el = element.parent().find('.accordion-body');
        if ($el.length > 0) {
          $el.prepend($tagsElement);  
        }
      } else {
        $tagsElement.empty();
      }
    }

**Comment by uggrock** [comment]
fixed for the next release (2.7)
