### ISSUE TITLE
have options in how metadata are stored

### ISSUE THREAD

**Issue by nrolland** [tagspaces/tagspaces#413]
Currently changing filenames is very problematic to say the least, as every OS out there really on the idea that "everything is a file" which is identified by ... a name. So anywhere your data is used somewhere else, this scheme breaks.

It would be much better to target some storage abstraction, and let people choose different backend : 
- metadata system provided by the OS
- side file storing metadata
- in the file itself for format which support it
- in a sqllite database
- ..

(hope that's not a duplicate)

**Comment by uggrock** [comment]
We are planning to release a PRO version of TagSpaces in the coming weeks, supporting sidecar files as alternative store for meta data.

**Comment by nero777x** [comment]
@uggrock Based on all the other writings I've seen in this repo, it appears that there is no intention of supporting a DBMS as a datastore in the future.  I like the sidecar files but it would be nice to have something a little more centralized.  Such a solution could be rigged cheaply with a single indexing file listing every .ts directory, I suppose.  But a DBMS, specifically something like Sqlite, would be a more approachable and clean solution.  If a contributor implemented such a feature would the TagSpaces team consider allowing it or is that completely out of scope for this project?

**Comment by uggrock** [comment]
We can imagine to integrate a database but only for speeding up the searching and implementing a real full text search. But in this case I will prefer a kind of nosql database. 
Saving the meta information (tags, description) in a non-centralized way, give you the freedom to just take a folder with tagged files and move it to another pc, syncing to a cloud or just archive it without fearing that you loose the meta information. Having this information only in a database is very restricting....

**Comment by nallj** [comment]
I don't think I was clear enough with my thoughts.  I wouldn't want to supplant the decentralized methods of tagging (sidecar and file naming).  I would merely like to add as an additional option the ability to keep track of tags within a database.  The reason why I would like this additional functionality is to allow a user to build their own applications that makes use of the centralized database.  I don't particularly care either way if it's SQL or NoSQL.  But it does need to be centralized to support such a use case.  Otherwise, anyone trying to build a third-party app that makes use of their tag information would have to implement their own search functionality and that would be undesirable for several reasons.

Perhaps the correct way to approach this would be to build an interface for supporting DBMS within the TS core.  Then different implementations of databases can be built as an extension.  I haven't looked at code for any of the extensions so I'm not even sure if that's even feasible.  But it sounds like a good compromise on the surface.
