### ISSUE TITLE
What about metadata?

### ISSUE THREAD

**Issue by bennypr0fane** [tagspaces/tagspaces#423]
So I just read there is going to be a new version of TS that stores the tags in sidecar files instead of the filenames. I'm very much looking forward to trying it out - how is it coming along?

What I really want to ask about though is, have you considered metadata, and if yes, what were the reasons not to venture down that road?
I've been thinking that metadata must be the most portable and elegant way to manage tags, but haven't quite wrapped my head around how metadata really works, and whether or not cross-platformness is an issue.
So some metadata can change, depending on what filesystem a file is stored in, i.e. they're not portable. Then, different file types have different types and sets of metadata.
But couldn't tags be part of any use generated file's  metadata, regardless of filesystem and operating system?
I wonder if anyone has tried proposing a standard for that yet...

**Comment by i8degrees** [comment]
Hi there,

I, too, look forward to trying it out -- enough so to be a beta tester, if need be! :-) This is the one and only feature holding me back from adopting TagSpaces into my life.

@bennypr0fane Yes, there has been various propositions over the years, although I can only think of one off the top of my head: [OpenMetaApplications](https://code.google.com/archive/p/openmeta/wikis/OpenMetaApplications.wiki)

Some of the reasons why the developers of TagSpaces may have chosen against using extended attributes is, in no particular order:

* Extended filesystem attributes must be supported by the underlying filesystem and enabled. Every implementation that I'm aware of uses the file's inode to store the information. This means additional allocation of bytes for the filesystem (last I knew, 128-256 bytes was common), decreasing the total available space, regardless of if you are using it or not. Increasing the total inode space generally requires reformatting the filesystem. If you have access to a terminal, check this out:

```shell
# Show inode usage stats:
df -ih
# My output:
# Filesystem     Type   Inodes IUsed IFree IUse% Mounted on
# /dev/disk0s2   hfs       59M   36M   23M   62% /
# /dev/disk3     hfs      233M  179M   54M   77% /Volumes/Media
# /dev/disk4s2   hfs      348M  325M   24M   94% /Volumes/TM
# /dev/disk4s3   hfs       58M   54M  4.2M   93% /Volumes/OldTM
```

Guess what happens when you run out of inodes? Same consequences of running out of file disk space. Even more maddening, a regular disk usage report won't show you the problem, because you can still have free file space, but not be able to use it, due to having no available inodes left. If you aren't aware of the concept of all this, it can drive you mad.

* I have no clue as to how Windows handles any of this.

* Lastly, even if none of the above applies, you still have the operating system to deal with. This alone is a major issue, especially over time...

**DISCLAIMER:** My knowledge of these details may be off somewhat, because it has been a number of years since I've dealt with it in detail. Also, filesystems are free to handle inode allocation as they wish. I'd like to say that Apple's HFS separates the inode allocation to where you can run out of inodes, but still create new files (just without any additional metadata). I'm not entirely sure, though.

**Comment by Buena-Vista** [comment]
in NTFS on windows, the metadata for most file types (other than mp3 which have internal metadata) is stored in "add-ons" stored by the file system called streams.  if there's no metadata, then there is no extra disk usage per file, so that's not the problem.  but sadly if you copy your files to an exFAT formatted sd card or other non-NTFS file systems, the streams just disappear.  You do get a warning when doing the copy that you will be losing metadata....very dangerous approach since you could so easily lose all of your tags.  Now, I wouldn't mind having them in BOTH the file name, like now, and a utility to dump them into the official tags fields in windows so they'd show up and be sortable in windows file explorer.  but that's not really a huge benefit.

**Comment by uggrock** [comment]
In TagSpaces we try to utilize general solutions working on most of the operating systems the same way. That's we still use the name of the files as storage for tags and in the PRO you can choose to store the meta information in a separate sidecar file.
