### ISSUE TITLE
Bug (NTFS / Windows): path length limits restricts number of tags

### ISSUE THREAD

**Issue by larsborn** [tagspaces/tagspaces#455]
Under Windows / NTFS, the length of filenames (and paths) are pretty limited:

> Individual components of a filename (i.e. each subdirectory along the path, and the final filename) are limited to 255 characters, and the total path length is limited to approximately 32,000 characters. However, you should generally try to limit path lengths to below 260 characters (MAX_PATH) when possible. See http://msdn.microsoft.com/en-us/library/aa365247.aspx for full details
> (Source: http://stackoverflow.com/questions/265769/maximum-filename-length-in-ntfs-windows-xp-and-windows-vista)

This means, that I the number of tags (more precisely: the number of characters used for tags together with the number of characters in the filename) is limited too.

I'm aware, that this is a quite fundamental problem, that really is a problem of the file system in Windows. But I'm currently evaluating different tagging programs and TagSpace is perfect for our needs... except for this limitation, which sadly is a show-stopper. I'm also willing to contribute to the project but am a bit careful, since this probably has to be solved at a very low level of the application (and may also already be discussed a lot). So I wanted to get in touch with you before submitting a pull-request ;-). So my main questions are:
* is this problem well-known (and I may only not have found the corresponding ticket)
* are there already any approaches to solve this? If yes: what can I read to understand the approaches? If not: What is the best starting point to make contributions to this project? I would start with one or two smaller ones to learn the fundamentals of TagSpace and then make a suggestion to how to solve this problem.
* what would be the best location to discuss this? This issue? E-Mail? A chatroom?

Looking forward to your reply! :-)

**Comment by uggrock** [comment]
Hi,
this is known limitation of TagSpaces and it is not only on Windows, on OS X for example there is also a similar limitation. We believe that for general use like tagging photos in a relatively flat directory structure the 255 characters are enough. For advanced user we offer the TagSpaces PRO, where one of the features is the saving of the tagging/meta information in a sidecar files instead of renaming the files.

If you have some other ideas on how this issue can be solved, feel free to discuss it with us, we accept in general also pull-request.  You can reach us also on per email, which can be found on the our website.

kind regards,
Ilian

**Comment by larsborn** [comment]
Hi,
thanks for your reply. I didn't spot that feature in the featurelist. That is totally sufficient! Looking forward to using this great software.

Regards,
Lars
