### ISSUE TITLE
Issue with editing tags in tag library (changes do not propagate to tagged items)

### ISSUE THREAD

**Issue by megankstrait** [tagspaces/tagspaces#464]
I've created several tags, tagged several files, and then within the tag library gone to Edit Tag and modified the tag name.

However, the items tagged prior to the tag name modification do not reflect the changed name. Moreover, they show the previous name of the tag as a *new* tag and no longer select when the updated tag is selected.

**Comment by uggrock** [comment]
Since we do not use a database for saving the tagging information but just the filenames, it is not feasible to go through your locations and find and rename all you files with the new tag name.

**Comment by pfalcon** [comment]
> Since we do not use a database for saving the tagging information but just the filenames

Well, now you do have the database - those "sidecar" tag files in JSON (I really couldn't use Tagspaces before that). Not only you do have the database, you actually have UUID (unique id) for each tag, which makes consistent update of tag names trivial and precise.

@uggrock, this issue is effectively a blocker for any serious usage of Tagspaces. Any chance this this issue can be reopened and reconsidered? Thanks.

**Comment by uggrock** [comment]
We still do not have a database, but many JSON files somewhere in the user's filesystem...

**Comment by pfalcon** [comment]
> We still do not have a database, but many JSON files somewhere in the user's filesystem...

Thanks for the reply. The point is that now you could fix this issue (for the "sidecar" mode at least).
