### ISSUE TITLE
Can't add multiple tags at once, comma separation misinterpreted as unusable symabol

### ISSUE THREAD

**Issue by CCapra** [tagspaces/tagspaces#595]
I'd like to be able to add multiple tags at once - several clicks per tag is too much work, I won't keep using it in that case. 

The help text in the add-tag pop-up says 'comma separated list of tags', so I'd think what I want is intended. But when I try to do that, I get the following

![screenshot 2017-05-29 11 51 02](https://cloud.githubusercontent.com/assets/11077871/26557205/2703ce7e-4465-11e7-9de6-2bb1e5d3f612.png)

Thanks!

**Comment by uggrock** [comment]
Hi,
the list of tags should be really only comma separated, with no space after the comma. This is so because we are not allowing spaces in the names of the tags. In this dialog you are adding only tags to a so called tag group. 

You can learn more about file and folder tagging in our documentation: https://docs.tagspaces.org/tagging.html

regards,
Ilian

**Comment by CCapra** [comment]
Oh! I see! Thanks!
