### ISSUE TITLE
renaming tags

### ISSUE THREAD

**Issue by KIRINPUTRA** [tagspaces/tagspaces#607]
I found that when I rename a tag, the change doesn't apply to files that already have that tag. Am I doing it wrong? Is there any way to rename a tag system-wide?

**Comment by KIRINPUTRA** [comment]
I bought a license for the PRO version, but I still have this problem with not being able to rename a tag. Is there some way to at least select all files and folders with a certain tag, give them a new tag at the same time, and then delete the old tag?

I've been using tags for several years in OS X, Evernote, Firefox bookmarks, etc. Sometimes it's necessary to rename a tag.

**Comment by uggrock** [comment]
Hi, 
system wide renaming of tag is not possible, because the tags are not managed in centralized way, such as a database, and we have to search your whole hard drive, in order to try to rename the tags of tagged files.
To your second question, yes the proposed workflow is supported. You can select many files, then you can open the tagging dialog (ctrl/command+t) and type the name of the tag(s) you want to remove and click on the orange button 'remove tags'. Later on the same file selection, with the same dialog you can add new tags to your files.
![image](https://user-images.githubusercontent.com/1249777/28769493-1269ada0-75dc-11e7-9565-07bf438de699.png)

For more information you can refer to our documentation: https://docs.tagspaces.org/tagging.html#tagging-using-context-menus
