### ISSUE TITLE
Suggestions for future features

### ISSUE THREAD

**Issue by prog20901** [tagspaces/tagspaces#629]
Having tags for each document (Reference: https://collatenotes.com/)
Built in web clipper (save webpages locally) - (Reference: https://collatenotes.com/)
Import data from Zim Wiki or Text files - (Reference: https://collatenotes.com/)
Google like search like ambar cloud (Reference: https://ambar.cloud/)
Function Keys support to navigate previous/next hit like Folio Views
Number of search results before search performed like table (Reference: http://table.branham.org/#/main)
Support for full text search in huge text nodes - example atleast 10,000 nodes with 100 kb of text each. Most note-taking software couldn't handle such huge content due to missing indexing
Quickest search results via indexing through Apache Lucene like docFetcher (http://www.techrepublic.com/blog/linux-and-open-source/portable-desktop-search-make-the-most-of-docfetcher/)
Please go through the menus of cherry tree software and incorporate which is easly doable.
drag and drop support between nodes

**Comment by Hugo-KTM** [comment]
+
Option to put tags in extended attributes (*x) or alternate data streams (win), offer export function that can convert to sidecar or renaming.
I can't have a tool that renames files or adds folders, hidden or not, because of file links, think Excel, Word, other users and so on.
I would like to be able to suggest a tool to colleagues which "magically" stores additional information for files (tags) and allows to use those to navigate and find stuff.

**Comment by uggrock** [comment]
web clipper is implemented, the rest issues are enhancement requests...
