### ISSUE TITLE
Selecting files with Shift and Ctrl

### ISSUE THREAD

**Issue by Sidewinder53** [tagspaces/tagspaces#686]
I've seen this mentioned before, but is there any chance we'll get keyboard support for selecting multiple files? Something like the usual Shift + Click to select all files in between and Ctrl + Click to select individual items would be incredibly handy!

I understand that this might not be useful for everybody, but looking at the big "cloud file managers" it's a feature that's almost always implemented. 

Thanks!

**Comment by omsshaheen** [comment]
I can trace back requests for shift/control selection controls that go back years!
It is an essential part of any browser and since there are no embedded tagging controls outside the application browser it is a MUST have if tagspaces would like to be classified as a standard utility rather than more of a gimmick that you cannot easily recommend without pointing out all the limitations.

**Comment by arcandio** [comment]
Related to #689

**Comment by arcandio** [comment]
Between this and #689, I'm considering building my own script solution to replace my usage of TagSpaces, because I don't want to waste all the time and frustration of trying to multiselect hundreds of files at a time without Shift-selecting runs.

**Comment by uggrock** [comment]
implemented in version 3.0.7
