### ISSUE TITLE
Feature requests: WYSIWYG  RTF editor and Auto edit files

### ISSUE THREAD

**Issue by gasparschott** [tagspaces/tagspaces#711]
It would be great if editable file types could be edited as soon as they are selected, instead of having to open the preview and then click to edit.

The ability to edit RTF files would be excellent as well.

**Comment by Stele77** [comment]
I have known Tagspaces nearly since the first public release AFAIK, and the missing rich text support or ODT (not to speak of doc/docx) support has been the one thing that did always hold me back from using it as daily driver and buying a sub. I always come back and check the status of this feature once a year, with no luck sadly.
It has been requested before, and i read there are technical problems preventing it. But using Tagspaces as document manager with edit feature would make it worth the money for me. Without it, there isn't much benefit for me. 
If you know markdown, or want to use HTML as RTF replacement, you could work around this limitation though..

**Comment by uggrock** [comment]
editing RTF file will not be in the scope of the TagSpaces -> closing
