### ISSUE TITLE
.ts folder is created in every folder and sub-folder on click in location manager

### ISSUE THREAD

**Issue by flo82** [tagspaces/tagspaces#786]
Actual Behaviour: 

every time a folder (e.g. "test") is clicked in the location manager a folder named ".ts" is created and contains nothing.
furthermore if a subfolder (e.g. "test/sub") is clicked a new folder namen ".ts" is created under the subfolder.

Expected behaviour:

no folder is created automatically.

**Comment by hasues** [comment]
I guess I would at least like to understand why it is created? Is this how the sidecar system is implemented?  Anyone use sidecar files?

**Comment by uggrock** [comment]
The .ts folder are needed for the sidecar tagging, for the file and folder description and for the generation of the thumbnails. There is for a sure a way to create .ts only when we need them, but this requires a deep change of the application and could potentially slow down the application, because we have to check before every operation if this folder is existing. Now it is created automatically on a opening of a folder in the application.

**Comment by flo82** [comment]
sidecar tagging is disabled in my options. you could actually check for that option and only if the option is tagged, create the .ts folder. so no i/o filesystem access needed. would be happy that you think about it.

**Comment by uggrock** [comment]
fixed in 3.2.5
