### ISSUE TITLE
Managing large folder structure with many files

### ISSUE THREAD

**Issue by Jhsmit** [tagspaces/tagspaces#788]
I'd like to manage a folder wtih ~5000 subfolders and ~50k files with tagspaces. When I add the whole I folder in tagspaces my processor is pretty much lit on fire. I was able to get it to be managable by just adding a subfolder and playing around with some of the setings. 

Which of the location settings are important for performance? Does 'Switch to manual index creation with persisted search index' improve performance? 

I've turned off thumbnail generation and I'm using tagspace pro v3.0.0-rc6.

**Comment by uggrock** [comment]
Every time you open the location with the 50k, TagSpaces starts to index these files in background. This could be time consuming, but is done on a separate process as the main process of the app. So it should be usable in this time. The idea of the indexing every time is to ensure that the index is up to date. If these 50k files are not changing very offen, you can active the "Switch to manual index creation....". So here once the index is done it will be persisted in the .ts folder of the location and loaded on location opening. 

Thumbs are generated only once by the opening of a folder, and only for the current folder without the subfolders.

**Comment by Jhsmit** [comment]
I've added the whole folder now and sitched to manual index creating. It works quite smoothy now, i had some error messages about index not succesfully loaded or something along those lines before but they have dissapeared. 

What does the watch for external changes do exactly?

**Comment by uggrock** [comment]
If you activate this feature for a certain location, TagSpaces will register external operations such as rename and delete on the files in this location and will try to reflect these operations. So if for example you have connected a Dropbox folders to TagSpaces and you rename a files on some other device, after the sync process, this rename will be shown in TS. The index of the files the current location will be also updated, in order to get correct search results.
