### ISSUE TITLE
Tag Colours

### ISSUE THREAD

**Issue by kwa11ace** [tagspaces/tagspaces#799]
Just noticed (RC8, Windows 10) that when you change the colour of the tag group the tags under it do not change colour nor the tags added to files.

Also when making tags, if you have a tag with a space in it it will look OK on the tag index but will come out as 2 tags when adding them to a file (not sure is feature).

![2018-12-20_15h31_39](https://user-images.githubusercontent.com/28090400/50270509-bd467080-046c-11e9-8a81-f2f2c2b78756.png)

**Comment by uggrock** [comment]
Thanks for reporting this

**Comment by GustJc** [comment]
If you change a single tag color. 
When you are drag-dropping it on windows x64 version the transparent preview of the tag over the mouse still remains the old color. On version 3.0.0

Also, the tags already in use don't change color. Same happens when renaming. The already set tags retains the name and the program treats as if you created a new tag with no association with anything. But I don't know if that was supposed to be a feature or not.

**Comment by hugopeek** [comment]
> Also, the tags already in use don't change color. Same happens when renaming. The already set tags retains the name and the program treats as if you created a new tag with no association with anything. But I don't know if that was supposed to be a feature or not.

I think this behaviour was the same in previous versions. I would personally prefer that the changes to a tag are applied to all existing tags too (color + text), but can image that that's a tricky thing to develop.

**Comment by uggrock** [comment]
We are currently looking for a solution for the tag color issue ....

**Comment by uggrock** [comment]
fixed in 3.0.1
