### ISSUE TITLE
Prev/Next in Folder View not updating file viewer

### ISSUE THREAD

**Issue by sbenders-c3iot** [tagspaces/tagspaces#916]
**Describe the bug**
After binding Prev/Next to keyboard keys... using prev/next keys after selecting a file does not update the previewer with currently selected/active file.

**To Reproduce**
1. Go to file viewer
2. Click on a file (like image.jpg) to open the preview
3. Use next/prev keys to select next/prev file in folder view
4. See preview does not update to currently active file in folder view

**Expected behavior**
Preview should update to match currently selected/active file in folder view.

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.13.6
 - Browser: Chrome
 - Version: TagSpaces: 3.0.9 / BuildID 4444f22829d| Chrome: Version 72.0.3626.109 (Official Build) (64-bit)

**Additional context**
This behaves as expected only if you first click the UI Buttons in the Previewer for Open Prev/Next file.

**Comment by hugopeek** [comment]
I noticed the same thing. The preview is updated when pressing Enter after using prev/next buttons, but that's not really comfortable when you are browsing an image folder for example. Preferred behaviour should be as outlined above.

I was also wondering if it's possible to change prev/next button bindings to arrow keys (instead of ',' and '.'), but I guess that would need a separate issue..

**Comment by uggrock** [comment]
this is fixed in the recent version -> closing
