### ISSUE TITLE
PDF background/foreground colour selection

### ISSUE THREAD

**Issue by EchoBetaGlass** [tagspaces/tagspaces#918]
**Is your feature request related to a problem? Please describe.**
I love the dark theme for the application. However it would be nice it the theme extended to documents such as PDFs.

**Describe the solution you'd like**
An option to choose to change the document colours with the global application theme would be nice. An option to choose whatever set of colours we want, regardless of the application theme would be ideal.

**Describe alternatives you've considered**
I currently go outside the application and use okular to view pdfs.

**Comment by uggrock** [comment]
Implementing such a feature for PDF is kind of braking the idea of the PDF format, that the document should look the same on every platform. TagSpaces was never intended to be a full fledged PDF reader, we build-in a bare minimum functionality in order to allow the users to preview the documents there... 

If somebody has the ability to implement such feature, we are accepting PRs on https://github.com/tagspaces/viewerPDF
