### ISSUE TITLE
Tagspaces-web v3.1.1: missing load of .ts/tsm.json for main folder

### ISSUE THREAD

**Issue by disaster123** [tagspaces/tagspaces#923]
Today i upgraded from tagspaces-web 2.9 to v3.1.1. Great new Design by the way ;-)

I than noticed that tagspaces no longer loads my tsm.json in the main directory. While the indexing processes and trys to find .ts/tsm.json in all subfolders it does not try to load the file in the main directory.

Greets,
Stefan

**Comment by uggrock** [comment]
Hello Stefan,
and thanks for the feedback. The main purpose of the tsm.json file is to contain tags with which a folders is tagged and the folder description. We have the impression that loading custom tag groups from tsm,json was not widely used because it was not easy to setup, so we decided not to migrate this features in version 3.0. I will keep the issue open for some weeks to see if there are other users wanting this feature back.

kind regards,
Ilian

**Comment by disaster123** [comment]
Oh i did not expect that. I‘m using tagspaces on multiple computers (home, laptop, my wife laptop) to Tag personal documents. So it was important to have the same tags on all computers.
Is there another way to achieve this?

**Comment by JotaPin** [comment]
Hi,
I was considering to use tagspaces on a shared drive with 20 people, but how can we share a common set of tags (tags group) without a tsm.json file being loaded?
Best regards, Jota

**Comment by aanatoly** [comment]
Please bring this feature back - it was super-useful

**Comment by uggrock** [comment]
the webdav version is not supported anymore -> closing
