### ISSUE TITLE
TagSpaces Pro 3.1.4 on macOS crashes on start (Library missing)

### ISSUE THREAD

**Issue by skrysmanski** [tagspaces/tagspaces#971]
**Describe the bug**
On my MacBook, TagSpaces Pro simply crashes on start. The non-pro version worked.

**To Reproduce**
1. Simply launch TagSpaces

**Expected behavior**
It should not crash.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.4
 - Version: 3.1.4

**Additional context**
The full error message is:

```
Process:               TagSpaces [11942]
Path:                  /Applications/TagSpaces.app/Contents/MacOS/TagSpaces
Identifier:            org.tagspaces.desktopapp
Version:               3.1.4 (3.1.4)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           TagSpaces [11942]
User ID:               501

Date/Time:             2019-04-25 18:03:34.054 +0200
OS Version:            Mac OS X 10.14.4 (18E226)
Report Version:        12
Anonymous UUID:        A03A0157-BADC-F240-E6B4-FEE0795FB1EF

Sleep/Wake UUID:       3D3515B6-1309-4DD5-8C18-5775BE6B8006

Time Awake Since Boot: 84000 seconds
Time Since Wake:       2500 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/TagSpaces.app/Contents/MacOS/TagSpaces
  Reason: no suitable image found.  Did find:
	/Applications/TagSpaces.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/TagSpaces.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x108049000 -        0x108049ffb +org.tagspaces.desktopapp (3.1.4 - 3.1.4) <6E272AEB-51ED-363B-B2D0-1E8B0C094EDF> /Applications/TagSpaces.app/Contents/MacOS/TagSpaces
       0x114192000 -        0x1141fc6ef  dyld (655.1.1) <F217F7F8-A795-3109-B77F-B1E2277F3E3B> /usr/lib/dyld
    0x7fff47145000 -     0x7fff47145fff  com.apple.Cocoa (6.11 - 23) <C487E1FC-D79C-32B4-950E-68F3060A125E> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff49bcd000 -     0x7fff49f7aff3  com.apple.Foundation (6.9 - 1570.16) <84055403-9921-3EFC-B593-8F0600EBEE80> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff4a282000 -     0x7fff4a311fff  com.apple.framework.IOKit (2.0.2 - 1483.250.15) <1170EC49-1912-3657-9C71-991653959191> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff52e58000 -     0x7fff53156ff7  com.apple.security (7.0 - 58286.251.4) <2084C515-AD64-3A48-BE3E-811CAA5A0E41> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff535b1000 -     0x7fff5361efff  com.apple.SystemConfiguration (1.17 - 1.17) <90F4626B-F9F6-377C-AA62-B8C23E857244> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
```

**Comment by syrabo** [comment]
Is there a solution. I have the problem with the 3.1.6 pro like free version

>Process:               TagSpaces [2128]
Path:                  /Users/USER/*/TagSpaces.app/Contents/MacOS/TagSpaces
Identifier:            org.tagspaces.desktopapp
Version:               3.1.6 (3.1.6)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           TagSpaces [2128]
User ID:               502

Date/Time:             2019-07-26 10:52:31.683 +0200
OS Version:            Mac OS X 10.14.6 (18G84)
Report Version:        12
Anonymous UUID:        90A4CF22-0FCC-779B-66D3-7CA2DCF9BDE6


Time Awake Since Boot: 2700 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Users/USER/*/TagSpaces.app/Contents/MacOS/TagSpaces
  Reason: no suitable image found.  Did find:

**Comment by uggrock** [comment]
Issue is fixed in the last few releases.
